// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5yZtL_0eZo2NewbNwXi2RX2hxl6c4Eyw',
    appId: '1:654539908326:web:0b16e06f2f193d1c520727',
    messagingSenderId: '654539908326',
    projectId: 'ecommerceapp-59249',
    authDomain: 'ecommerceapp-59249.firebaseapp.com',
    storageBucket: 'ecommerceapp-59249.firebasestorage.app',
    measurementId: 'G-MGP4XKY6CM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdyQyJZGsGQYqlRUBrKQWAH7Jlr5WiZ5Q',
    appId: '1:654539908326:android:7aa9480d1b3c9eac520727',
    messagingSenderId: '654539908326',
    projectId: 'ecommerceapp-59249',
    storageBucket: 'ecommerceapp-59249.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHiJ6E-A0YW6sDAw_5VJp63jPOduZh08g',
    appId: '1:654539908326:ios:ad9bf616f9ad313a520727',
    messagingSenderId: '654539908326',
    projectId: 'ecommerceapp-59249',
    storageBucket: 'ecommerceapp-59249.firebasestorage.app',
    androidClientId: '654539908326-vevj4ljs8j1qahah051sberb5f47ro4m.apps.googleusercontent.com',
    iosClientId: '654539908326-ctjha5s6aqenrllebe1h11vbq6egmser.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerseproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5yZtL_0eZo2NewbNwXi2RX2hxl6c4Eyw',
    appId: '1:654539908326:web:c5e2f9e553e5ea3f520727',
    messagingSenderId: '654539908326',
    projectId: 'ecommerceapp-59249',
    authDomain: 'ecommerceapp-59249.firebaseapp.com',
    storageBucket: 'ecommerceapp-59249.firebasestorage.app',
    measurementId: 'G-BT4KYNHBZD',
  );

}